name: 'Laravel CI/CD Action'
description: 'A custom GitHub Action for Laravel CI/CD'
author: 'Basant Singh Dobal (sbasant12345@gmail.com)'
inputs:
  production-branch:
    description: 'The production branch to deploy'
    required: true
    default: 'production'
  vps-host:
    description: 'VPS host'
    required: true
  vps-username:
    description: 'VPS username'
    required: true
  vps-private-key:
    description: 'VPS private key'
    required: true
  deploy-path:
    description: 'Deployment path on the VPS'
    required: true
    default: '/var/www/html/project_name/'
  php-version:
    description: 'PHP version to use'
    required: true
    default: '8.0'
outputs:
  deployment-status:
    description: 'The status of the deployment'
    value: ${{ steps.deploy.outputs.status }}
runs:
  using: 'composite'
  steps:
    - name: Set up job
      run: |
        case ${{ inputs.job }} in
          ci)
            ./entrypoint.sh ci
            ;;
          code_cleanup)
            ./entrypoint.sh code_cleanup
            ;;
          cd)
            ./entrypoint.sh cd
            ;;
          *)
            echo "Invalid job"
            exit 1
            ;;
        esac
branding:
  icon: 'wind'
  color: 'blue'
