name: 'Laravel CI/CD'
description: 'A GitHub Action to run Laravel CI/CD and code cleanup tasks'
author: 'Basant Singh Dobal (sbasant12345@gmail.com)'
inputs:
  job:
    description: 'The job type to run (ci, cd, code_cleanup)'
    required: true
  vps_private_key:
    description: 'The private key for VPS'
    required: false
    default: ''
  vps_username:
    description: 'The username for VPS'
    required: false
    default: ''
  vps_host:
    description: 'The host for VPS'
    required: false
    default: ''
  deploy_path:
    description: 'The deployment path on VPS'
    required: false
    default: ''
  production_branch:
    description: 'The production branch to deploy'
    required: false
    default: 'main'
  php_version:
    description: 'The PHP version to use'
    required: false
    default: '8.0'
  github_token:
    description: 'GitHub token to create issues'
    required: true
  repo:
    description: 'GitHub repository in owner/repo format'
    required: true
runs:
  using: 'composite'
  steps:
    - run: ./entrypoint.sh
      shell: bash
      env:
        JOB: ${{ inputs.job }}
        VPS_PRIVATE_KEY: ${{ inputs.vps_private_key }}
        VPS_USERNAME: ${{ inputs.vps_username }}
        VPS_HOST: ${{ inputs.vps_host }}
        DEPLOY_PATH: ${{ inputs.deploy_path }}
        PRODUCTION_BRANCH: ${{ inputs.production_branch }}
        PHP_VERSION: ${{ inputs.php_version }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ inputs.repo }}
branding:
  icon: 'wind'
  color: 'blue'
